spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: lyamanava048
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog-master.yml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true

server:
  port: 8095